package com.insurance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleAccessoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAccessoryAllPropertiesEquals(VehicleAccessory expected, VehicleAccessory actual) {
        assertVehicleAccessoryAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleAccessoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAccessoryAllUpdatablePropertiesEquals(VehicleAccessory expected, VehicleAccessory actual) {
        assertVehicleAccessoryUpdatableFieldsEquals(expected, actual);
        assertVehicleAccessoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAccessoryAutoGeneratedPropertiesEquals(VehicleAccessory expected, VehicleAccessory actual) {
        assertThat(actual)
            .as("Verify VehicleAccessory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAccessoryUpdatableFieldsEquals(VehicleAccessory expected, VehicleAccessory actual) {
        assertThat(actual)
            .as("Verify VehicleAccessory relevant properties")
            .satisfies(a -> assertThat(a.getAccessoryId()).as("check accessoryId").isEqualTo(expected.getAccessoryId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getFactoryInstalled()).as("check factoryInstalled").isEqualTo(expected.getFactoryInstalled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleAccessoryUpdatableRelationshipsEquals(VehicleAccessory expected, VehicleAccessory actual) {
        assertThat(actual)
            .as("Verify VehicleAccessory relationships")
            .satisfies(a -> assertThat(a.getCar()).as("check car").isEqualTo(expected.getCar()));
    }
}
